app = "hokkoku-llm-verify-devin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  INTENT_THRESHOLD = "0.7"
  OPENAI_MODEL = "gpt-4o-mini"
  OPENAI_TIMEOUT_QA_MS = "5000"
  OPENAI_TIMEOUT_APPLY_MS = "10000"
  MAX_REPROMPTS = "2"
  CORS_ALLOW_ORIGINS = "*"
  MOCK_OPENAI = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
